### ISSUE TITLE
What is the difference with python-xxhash?

### ISSUE THREAD

**Issue by awesomebytes** [ifduyue/python-xxhash-cffi#1]
Hello, not really an issue, but I'm curious to know what is the difference with python-xxhash?

Is it faster? Is it more convenient? Maybe the python package has some disavantage vs this one?

Thank you.

**Comment by ifduyue** [comment]
@awesomebytes Hello,

python-xxhash was implemented using CPython API, while python-xxhash-cffi was using cffi

**Comment by adrianog** [comment]
is this faster than the CPython equivalent then?

**Comment by ifduyue** [comment]
@adrianog haven't benchmark them yet. Just use python-xxhash, no commits since Jan 19, 2019 in this repo.

**Comment by awesomebytes** [comment]
I ended (happily) using python-xxhash for a while. I'll close this issue as it will probably not get any further info :)
